### ISSUE TITLE
Docs: Explain CORS policy

### ISSUE THREAD

**Issue by bhelx** [extism/playground#26]
We should have a section somewhere that explains how CORS works with wasm / extism plugins and recommendations on how to serve and consume the code. Even if it just links to some known source.

**Comment by chrisdickinson** [comment]
I've transferred this issue from the [js-sdk](https://github.com/extism/js-sdk) repo. The extism team usually discusses this issue in the context of fixing #25 – I believe what's happened here is that GitHub started 403'ing `OPTIONS` requests in order to cut down on hot-linking from other domains, like the playground:

```shell
$ curl -sLI -X OPTIONS 'https://raw.githubusercontent.com/extism/extism/main/wasm/code.wasm'
HTTP/2 403
cache-control: no-cache
content-type: text/html; charset=utf-8
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 0
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:;
accept-ranges: bytes
date: Mon, 24 Jun 2024 23:57:01 GMT
via: 1.1 varnish
x-served-by: cache-pdx12332-PDX
x-cache: MISS
x-cache-hits: 0
x-timer: S1719273421.191710,VS0,VE4
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
x-fastly-request-id: c790ebcfc58453721e9b8d482cd251d27893c89e
expires: Tue, 25 Jun 2024 00:02:01 GMT
vary: Authorization,Accept-Encoding
```
